config/routes.rb
Localizator::Engine.routes.draw do
  get '/' => 'locales#index', as: :locales
  post '/update' => 'locales#update', as: :update_locales
  get '/download' => 'locales#download', as: :download_locales
  get '/reload' => 'locales#reload', as: :reload_locales
end

Rails.application.routes.draw do
  mount_localizator_routes
end

app/controllers/localizator/application_controller.rb
module Localizator
  class ApplicationController < ActionController::Base
    if Localizator.username && Localizator.password
      http_basic_authenticate_with name: Localizator.username, password: Localizator.password
    end

    def app
      Localizator.app
    end
  end
end

app/controllers/localizator/locales_controller.rb
require_dependency "localizator/application_controller"

require "localizator/app"

module Localizator
  class LocalesController < ApplicationController
    def index
      @filters = params[:filters]

      if @filters.present?
        options = {}
        options[:key] = /#{@filters["key"]}/ if @filters["key"].to_s.size > 0
        options[:text] = /#{@filters["text"]}/i if @filters["text"].to_s.size > 0
        options[:complete] = false if @filters["incomplete"] == "on"
        options[:empty] = true if @filters["empty"] == "on"

        @keys = app.store.filter_keys(options)
      else
        @filters = {}
        @categories = app.store.categories.sort
      end
    end

    def update
      translations = params[:translations]

      if translations.present?
        translations.each {|name, text|
          app.store.translations[name].text = text
        }
        app.save_translations
      end

      redirect_to locales_path(filters: params[:filters])
    end

    def download
      input_dir = Localizator.locales_path
      output_file = Tempfile.new(['locales', '.zip'])
      output_file.close
      ZipFileGenerator.new(input_dir, output_file.path).write

      send_file output_file.path
    end

    def reload
      FileUtils.touch(Rails.root.join('tmp', 'restart.txt'))
      redirect_to locales_path
    end
  end
end

app/views/layouts/localizator/application.html.erb
<!DOCTYPE html>
<html>
  <head lanf="en">
    <title>Localizator</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    "localizator/application", media: "all" %>
    <%= javascript_include_tag "localizator/application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/localizator/application/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href=<%= locales_url %>>Localizator</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form action=<%= locales_url %> method="get" class="navbar-form navbar-left">
        <div class="form-group">
          <label for="filters_key">Key:</label>
          <input id="filters_key" name="filters[key]" type="text" value="<%= @filters["key"] %>" class="form-control" />
        </div>


        <div class="form-group">
          <label for="filters_text">Text:</label>
          <input id="filters_text" name="filters[text]" type="text" value="<%= @filters["text"] %>" class="form-control" />
        </div>

        <div class="form-group">
          <input id="filters_incomplete" name="filters[incomplete]" type="checkbox" <%= "checked=checked" if @filters["incomplete"] == "on" %> class="form-control" />
          <label for="filters_incomplete">Incomplete</label>
        </div>

        <div class="form-group">
          <input id="filters_empty" name="filters[empty]" type="checkbox" <%= "checked=checked" if @filters["empty"] == "on" %> class="form-control" />
          <label for="filters_empty">Empty</label>
        </div>

        <button type="submit" class="btn btn-default">Search</button>
      </form>
      <div class="navbar-right">
        <a href='/' class='btn btn-default navbar-btn'>App</a>
        <a href=<%= reload_locales_path %> class='btn btn-default navbar-btn'>Reload</a>
        <a href=<%= download_locales_path %> class='btn btn-default navbar-btn'>Download</a>
      </div>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/localizator/locales/index.html.erb
<% if @filters.empty? %>
  <table class="categories" cellspacing="0">
    <% @categories.each do |name, category| %>
      <tr class="category <%= "incomplete" unless category.complete? %>">
        <td class="key">
          <a class="text" href="<%= locales_url %>?filters[key]=<%= Rack::Utils.escape("^#{category.name}") %>"><%= category.name %></a>
        </td>
      </tr>
    <% end %>
  </table>
<% else %>
  <form id="updateform" action="<%= update_locales_path %>" method="post">
    <% @filters.each do |filter, value| %>
      <input name="filters[<%= filter %>" type="hidden" value="<%= value %>"/>
    <% end %>

    <table class="table table-striped table-hover" cellspacing="0">
      <% @keys.each do |name, key| %>
        <tr class="key
          <%= "warning" unless key.complete? %>
          <%= "danger" if key.empty? %>
          ">
          <td class="key">
            <span class="text"><%= key.name %></span>
          </td>
          <td class="translations">
            <table class="locales">
              <% key.translations.sort_by(&:locale).each do |translation| %>
                <tr>
                  <td class="locale"><%= translation.locale %>:</td>
                  <td class="value">
                    <% if translation.text.nil? || translation.text.is_a?(String) %>
                      <textarea name="translations[<%= translation.name %>]" dir="auto" class="form-control"><%= Rack::Utils.escape_html translation.text %></textarea>
                    <% else %>
                      [read only]
                      <%= translation.text.class.name %>
                      <%= Rack::Utils.escape_html translation.text.inspect %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </table>
          </td>
        </tr>
      <% end %>
    </table>
    <input type="submit" id="save" value="Save" class="btn btn-primary pull-right" />

    <div class='clearfix'/>
  </form>
<% end %>